name: build java app

push on:
  - trigger

env:
  java_version= "11"

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java_version = '11'
          distribution = 'terumin'

    - name: build java
    - run: |
      mvn -v
      mvn -b package 

