name: build java app

on:
 push :
    branches: 
      - master

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          app-directory: simple-springboot-app
          

      - name: build java
        run: |
          mvn -v
          mvn -B package --file simple-springboot-app/pom.xml -DskipTests  
