name: build java app

on:
  push :
    branches: 
      - master

env:
  java_version= "11"

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java_version = '11'
          distribution = 'terumin'

      - name: build java
        run: |
          mvn -v
          mvn -b package     


